zookeeper:
  image: oddpoet/zookeeper
  hostname: zookeeper
  command:
    - "2181"
  ports:
    - "2181:2181"

kafka:
  image: wurstmeister/kafka
  hostname: kafka
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
   KAFKA_ADVERTISED_PORT: 9092
   KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
   KAFKA_HOST_NAME: 192.168.99.100

graphite:
  image: hopsoft/graphite-statsd
  ports:
   - "8000:80"
   - "2003-2004:2003-2004"
   - "2023-2024:2023-2024"
   - "8125:8125/udp"
   - "8126:8126"
   
logstash:
  image: logstash
  links:
   - zookeeper:zk
   - graphite
  volumes:
   - /c/Users/docker logs/logstash.d:/logstash.d
  command: "logstash -f /logstash.d/logstash.conf"
   

   
grafana:
  image: grafana/grafana
  ports: 
   - "3000:3000"
  links:
   - graphite